Notes
Nazarovv676/neo-team-proj1 pull request #3
Opened 2024-11-05 21:16 UTC by AnastasiaBndr

Зробила два класи, Note та NotesList за аналогом Record та AddressBook, додала можливості видаляти та додавати нотатки та поля keywords та tags. Помилки поки не обробляла окремо а просто робила raise Exception("текст помилки"). Серіалізацію теж не робила

2024-11-06 16:39 UTC, Nazarovv676 requested changes

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/__init__.py
> +from src.note.note import Note
У пакетах краще використовувати релятивні імпорти всередині пакетів. Це дасть змогу міняти місце знаходження цих пакетів у проєкті. 

```python
from .note import Note
from .notes_list import NotesList
```

2024-11-06 16:39 UTC, Nazarovv676 commented on addressbook.pkl
Цей файл завжди буде конфліктним тому що він бінарний (не текстовий). Краще додати його в `.gitignore`

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/fields/__init__.py
> +from src.note.fields.id import Id
Тут також імпорти можна зробити релятивними так як це пакет/модуль (є __init__.py)

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/fields/id.py
> +from src.address_book import Field
Краще цей клас винести з модуля address_book на рівень вище. Це допоможе пакету notes не залежати від address_book

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/note.py
> +    def __init__(self, name: str, id: int):
id зазвичай йду у першу чергу в параметрах, потім всі інші

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/note.py
> +            raise Exception("This keyword exists!")
Якщо є якісь частинки коду які треба оновити у майбутньому залишай коментар 
```python
# TODO: use here custom exception
raise Exception()
```

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/note.py
> +            raise Exception("This tag exists!")
Тут так само

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/notes_list.py
> +class NotesList(UserDict):
Це повинна бути колекція UserList

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/notes_list.py
> +        self.data[note] = NotesList.notes
З UserList тут буде інша логіка

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/notes_list.py
> +        notes = list(
І тут також буде інша логіка

2024-11-06 16:39 UTC, Nazarovv676 commented on src/note/notes_list.py
> +            raise Exception("invalid data format!")
Залиш коментар TODO

2024-11-08 09:09 UTC, Nazarovv676 commented on src/note/commands/add_note.py
> +    user = book.find(name)
Ти можеш прибрати цю перевірку. Нотатки поки що не треба привʼязувати до контактів. Також це не той спосіб привʼязки який ми планували реалізувати. Буде просто додавання нотатки у базу.

```python
@input_error
def add_note(args: list, notes: Notes) -> str:
    name, *description = args
    description_joined = ' '.join(description)

    note = Note(name, description_joined)
    notes.add_note(note)
    return MESSAGES["note_added"]
```

2024-11-08 09:09 UTC, Nazarovv676 commented on src/note/notes.py
> +            if len(self.data) == 0 and Notes.first_open:
Чому ти додала цю логіку? pickle не зберігає ids при перезавантаженні програми?

2024-11-08 12:55 UTC, Nazarovv676 approved these changes

2024-11-08 13:10 UTC, Mariia996 requested changes

2024-11-08 13:10 UTC, Mariia996 commented on src/note/commands/show_note.py
> +    if len(notes)==0:
Додай тут відступи спереду і після оператора або використай black на цьому файлі

2024-11-08 13:16 UTC, Mariia996 approved these changes

2024-11-08 13:41 UTC, merged