Add address and email functionality to bot
Nazarovv676/neo-team-proj1 pull request #6
Opened 2024-11-07 15:13 UTC by Yulia739

2024-11-07 15:25 UTC, Nazarovv676 requested changes

2024-11-07 15:25 UTC, Nazarovv676 commented on src/contacts_bot/commands/add_address.py
> +        raise AddressException(ERROR_MESSAGES["name_and_address_missing"])
Не бачу name_and_address_missing у ERROR_MESSAGES

2024-11-07 15:25 UTC, Nazarovv676 commented on src/contacts_bot/commands/add_email.py
> +        raise EmailException(ERROR_MESSAGES["name_and_email_missing"])
Не бачу name_and_email_missing у ERROR_MESSAGES

2024-11-07 15:27 UTC, Yulia739 commented on src/contacts_bot/commands/add_email.py
> +        raise EmailException(ERROR_MESSAGES["name_and_email_missing"])
Пофікшено

2024-11-07 15:28 UTC, Yulia739 commented on src/contacts_bot/commands/add_address.py
> +        raise AddressException(ERROR_MESSAGES["name_and_address_missing"])
Пофікшено

2024-11-07 16:10 UTC, Nazarovv676 approved these changes

2024-11-07 16:41 UTC, Mariia996 requested changes

2024-11-07 16:41 UTC, Mariia996 commented on src/contacts_bot/commands/show_all.py
> +            user.address.value if user.address else "No Address"
Я думаю що для кращої читабельності користувача заміть  `No Email ` і `No Address` варто виводити просто прочерк `-`

<img width="355" alt="Знімок екрана 2024-11-07 о 18 20 18" src="https://github.com/user-attachments/assets/632f4505-f8c6-47ff-b9d8-46682dba74df">

І так як ти вже додала email і address в табличку при відсутності даних то можна тоді і birthday з прочерком додати також😊

2024-11-07 16:43 UTC, AnastasiaBndr approved these changes

2024-11-08 13:01 UTC, Mariia996 approved these changes

2024-11-08 13:02 UTC, merged